# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('puesto', models.CharField(max_length=60)),
                ('numempleado', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
